id: P009098
initial_creation_type: ocr
source_metadata:
  id: bdr:W21864
  title: དུས་རབས་ཉེར་གཅིག་པའི་སྙིང་གཏམ།
  author: ''
  volumes:
    1c853a324fe647e7b7509f4f779446e3:
      image_group_id: I1KG22958
      title: ''
      volume_number: 1
      total_pages: 192
      base_file: v001.txt
