id: I1339E36D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:24:55+00:00'
last_modified: '2022-06-08T08:36:12.894288+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21864
  title: དུས་རབས་ཉེར་གཅིག་པའི་སྙིང་གཏམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B922:
      image_group_id: I1KG22958
      title: ''
      total_pages: 192
      order: 1
      base_file: B922.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
